---
directories:
  "lib/active_admin/resource":
    ModuleInitialize:
      enabled: false

  "lib/active_admin/axlsx":
    Attribute:
      enabled: false
    ControlParameter:
      enabled: false
    DuplicateMethodCall:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false
    ManualDispatch:
      enabled: false
    NilCheck:
      enabled: false
    TooManyInstanceVariables:
      enabled: false
    TooManyMethods:
      enabled: false
    UtilityFunction:
      enabled: false

  "lib/log":
    DuplicateMethodCall:
      enabled: false
    IrresponsibleModule:
      enabled: false
    ManualDispatch:
      enabled: false
    UtilityFunction:
      enabled: false
    ControlParameter:
      enabled: false
    FeatureEnvy:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    LongParameterList:
      enabled: false
