inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
AllCops:
  Exclude:
    - db/**/*
    - script/**/*
    - vendor/**/*
    - bin/**/*
    - test/**/*
    - lib/active_admin/axlsx/**/*
    - tmp/**/*
  TargetRubyVersion: 3.0

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - staging
    - test

Style/Documentation:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 3

Metrics/MethodLength:
  Severity: warning
  Max: 25

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 200
  Exclude:
    - app/admin/*.rb

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 130

Naming/FileName:
  Exclude:
    - Gemfile
    - Guardfile

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Exclude:
    - config/**/*

Style/Semicolon:
  Exclude:
    - app/views/families/new_spreadsheet/**/*
    - app/views/ministries/**/*
    - app/views/housing_facilities/new_spreadsheet.html.arb

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
