inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*
    - script/**/*
    - vendor/**/*
    - bin/**/*
    - test/**/*
    - lib/active_admin/axlsx/**/*
    - tmp/**/*

  TargetRubyVersion:
    2.5

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - staging
    - test

Documentation:
  Enabled: false

GuardClause:
  MinBodyLength: 3

Lint/RescueException:
  Exclude:
    - app/jobs/**/*

MethodLength:
  Severity: warning
  Max: 25

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 200
  Exclude:
    - app/admin/*.rb

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 130

Naming/FileName:
  Exclude:
    - Gemfile
    - Guardfile

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: False

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Exclude:
      - config/**/*

Style/Semicolon:
  Exclude:
    - 'app/views/families/new_spreadsheet/**/*'
    - 'app/views/ministries/**/*'
    - 'app/views/housing_facilities/new_spreadsheet.html.arb'

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
