class CostAdjustment < ActiveRecord::Base
  belongs_to :person, foreign_key: 'person_id'

  # Override the generated setter to strip non-digits generated by
  # jquery-price_format script
  def cents=(cents)
    if cents.is_a?(String)
      super(cents.gsub(/\D/, '').to_i)
    else
      super
    end
  end
end
